# 1. Nombre de la aplicación
spring.application.name=servicio-estudiantes

# 2. Configuración de la Base de Datos (Gasolina para el motor)
# El localhost:3306 es la dirección de tu Docker.
# db_estudiantes es el nombre de la base de datos que se creará.
spring.datasource.url=jdbc:mysql://localhost:3306/db_estudiantes?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Configuración de Liquibase (El control de versiones de la BD)
# Aquí le decimos dónde está el "Director de Orquesta" que creamos antes.
spring.liquibase.change-log=classpath:db/changelog/maestro.xml
spring.liquibase.enabled=true

# 4. Mostrar el SQL en la consola (Para que veas lo que pasa por detrás)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none