spring:
  application:
    name: api-gateway
  profiles:
    active: ${APP_PROFILE:dev}
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - PreserveHostHeader
          routes:
            - id: ruta-estudiantes
              uri: lb://SERVICIO-ESTUDIANTES
              predicates:
                - Path=/api/v1/estudiantes/**

            - id: ruta-profesores
              uri: lb://SERVICIO-PROFESORES
              predicates:
                - Path=/api/v1/profesores/**

            - id: ruta-asistencias
              uri: lb://SERVICIO-ASISTENCIAS
              predicates:
                - Path=/api/v1/asistencias/**

            - id: ruta-cursos
              uri: lb://SERVICIO-CURSOS
              predicates:
                - Path=/api/v1/cursos/**

            - id: ruta-asignaturas
              uri: lb://SERVICIO-ASIGNATURAS
              predicates:
                - Path=/api/v1/asignaturas/**

            - id: ruta-matriculas
              uri: lb://SERVICIO-MATRICULAS
              predicates:
                - Path=/api/v1/matriculas/**

            - id: ruta-biblioteca
              uri: lb://SERVICIO-BIBLIOTECA
              predicates:
                - Path=/api/v1/biblioteca/**

            - id: ruta-finanzas
              uri: lb://SERVICIO-FINANZAS
              predicates:
                - Path=/api/v1/finanzas/**

            - id: ruta-notificaciones
              uri: lb://SERVICIO-NOTIFICACIONES
              predicates:
                - Path=/api/v1/notificaciones/**

            - id: ruta-calificaciones
              uri: lb://SERVICIO-CALIFICACIONES
              predicates:
                - Path=/api/v1/calificaciones/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka/}

server:
  port: ${GATEWAY_PORT:8090}

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

logging:
  level:
    root: info
    com.duoc: info
    org.springframework.cloud.gateway: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: "logs/${spring.application.name}.log"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
