# 1. Nombre de la aplicación
spring.application.name=gateway

spring.cloud.gateway.routes[0].id=servicio-estudiantes
spring.cloud.gateway.routes[0].uri=lb://SERVICIO-ESTUDIANTES
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8080