spring.application.name=servicio-cursos
server.port=8084

# Debe coincidir con server.port de servicio-profesores (mismo host + path base del API)
feign.profesores.url=http://localhost:8082/api/profesores

spring.datasource.url=jdbc:mysql://localhost:3306/db_cursos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.liquibase.change-log=classpath:db/changelog/maestro.xml
spring.liquibase.enabled=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
