spring.application.name=servicio-calificaciones

# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/calificaciones?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=my-secret-pw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA - Delega esquema a Flyway
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Flyway - Migraciones
spring.flyway.enabled=true
spring.flyway.repair=true
